spring.application.name=ferreteria

# SQLite crea un archivo local sin requerir un servidor de base de datos.
spring.datasource.url=jdbc:sqlite:./ferreteria.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.open-in-view=false